baseURL = 'https://cryptobyday.net/'
languageCode = 'en-us'
title = 'Crypto by Day'
theme = '2025'
disableHugoGeneratorInject = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[taxonomies]